name: UI Tests (Cypress + Allure)

on:
  push:
    paths:
      - 'cypress/**'
      - '.github/workflows/ui-tests.yml'
  workflow_dispatch:

jobs:
  ui:
    runs-on: ubuntu-latest

   
    defaults:
      run:
        working-directory: cypress

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: cypress/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Run Cypress headless (Chrome)
        run: npx cypress run --browser chrome --headless

      - name: Upload Cypress artifacts (videos/screenshots)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          if-no-files-found: ignore
          path: |
            cypress/videos/**/*
            cypress/screenshots/**/*

      - name: Generate Allure HTML
        if: always() && ${{ hashFiles('cypress/allure-results/**') != '' }}
        run: npx allure generate allure-results --clean -o allure-report

      - name: Upload Allure HTML
        if: always() && ${{ hashFiles('cypress/allure-report/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          if-no-files-found: ignore
          path: cypress/allure-report
